version: '3'

services:
  api:
    container_name: 'api'
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - .:/usr/app
    command: npm run start:dev
