version: '3'

services:
  api:
    container_name: 'api'
    build: .
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_PORT: ${SERVER_PORT}
    volumes:
      - .:/usr/app
      - ./node_modules:/usr/app/node_modules
    depends_on:
      - mysql
    links:
      - mysql
    command: sh -c "npx prisma migrate dev && npm run start:dev"

  mysql:
    image: mysql:5.7
    container_name: 'database'
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    expose:
      - ${DATABASE_PORT}
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
