name: Continuos Integration

on:
  push:
    branches:
      - main

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: todos
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Using Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1

      - name: Install Dependencies
        run: |
          npm install
          npm install -g prisma

      - name: Run Prisma
        run: |
          npx prisma generate

      - name: Run Tests
        run: npm run test
        env:
          DATABASE: supertest
          DATABASE_HOST: localhost
          DATABASE_URL: 'mysql://root:password@localhost:3306/supertest?schema='
