name: Continuos Integration

on:
  push:
    branches:
      - main

env:
  SERVER_PORT: 3000
  DATABASE: todos
  DATABASE_PORT: 3306
  DATABASE_PASSWORD: password
  DATABASE_URL: 'mysql://root:password@mysql:3306/todos'

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Creating network
        run: docker network create "network"

      - name: Build docker-composer
        run: docker-compose up -d

      - name: Wait for node_modules
        run: |
          until docker exec api [ -d "node_modules" ] && [ "$(ls -A node_modules)" ]; do
            sleep 1
          done

      - name: Run Tests
        run: docker exec api npm test
