name: Continuos Integration

on:
  push:
    branches:
      - main

env:
  SERVER_PORT: 3000
  DATABASE: todos
  DATABASE_PORT: 3306
  DATABASE_PASSWORD: password
  DATABASE_URL: 'mysql://root:password@mysql:3306/todos'

jobs:
  continuos-integration:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: todos
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Run MySQL Query
        run: |
          mysql -h127.0.0.1 -uroot -ppassword -e "SHOW DATABASES;"
